jam_notas_frontend:
    resource: "@JAMNotasFrontendBundle/Resources/config/routing.yml"
    prefix:   /notas
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
jam_notas_backend:
    resource: "@JAMNotasBackendBundle/Resources/config/routing.yml"
    prefix:   /

jazzyweb_aulas_mentor_alimentos:
    resource: "@JazzywebAulasMentorAlimentosBundle/Resources/config/routing.yml"
    prefix:   /alimentos

user_routes:
    resource: "@UserBundle/Controller"
    type: annotation
    
JAMNotasFrontendBundle_tarifa:
        resource: "@JAMNotasFrontendBundle/Resources/config/routing/tarifa.yml"
        prefix:   /notas/tarifa
        
